pictweet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tweetapp/urls.py
from django.urls import path
from .views import PicList, PicDetail, PicCreate, PicDelete, PicUpdate, SignUpView

app_name = 'tweetapp'

urlpatterns = [
    path('list/', PicList.as_view(), name='list'),
    path('detail/<int:pk>', PicDetail.as_view(), name='detail'),
    path('create/', PicCreate.as_view(), name='create'),
    path('delete/<int:pk>', PicDelete.as_view(), name='delete'),
    path('update/<int:pk>', PicUpdate.as_view(), name='update'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
]

tweetapp/models.py
from django.db import models

# Create your models here.

class PicTweetModel(models.Model):
    title = models.CharField(max_length=100)
    coment = models.TextField(null=True, blank=True)
    pic = models.ImageField(upload_to='')
    author = models.CharField(max_length=100, null=True, blank=True)

tweetapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import PicTweetModel
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


class PicList(LoginRequiredMixin, ListView):
    template_name = 'list.html'
    model = PicTweetModel


class PicDetail(LoginRequiredMixin, DetailView):
    template_name = 'detail.html'
    model = PicTweetModel
    context_object_name = 'item'


class PicCreate(LoginRequiredMixin, CreateView):
    template_name = 'create.html'
    model = PicTweetModel
    fields = (
        'title',
        'coment',
        'pic',
        'author',
    )
    success_url = reverse_lazy('tweetapp:list')


class PicDelete(LoginRequiredMixin, DeleteView):
    template_name = 'delete.html'
    model = PicTweetModel
    context_object_name = 'item'
    success_url = reverse_lazy('tweetapp:list')


class PicUpdate(LoginRequiredMixin,UpdateView):
    template_name = 'update.html'
    model = PicTweetModel
    fields = (
        'title',
        'coment',
        'pic',
    )
    success_url = reverse_lazy('tweetapp:list')


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    {% block customcss %}
    {% endblock customcss %}

    <title>PicTweet</title>
  </head>
  <body>
    {% block header %}
    {% endblock header %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-dark" role="alert">
新規投稿
</div>
{% endblock header %}

{% block content %}
<form action='' method='POST' enctype='multipart/form-data'>{% csrf_token %}
  <p>タイトル:<input type='text' name='title'></p>
  <p>コメント:<input type='text' name='coment'></p>
  <p>画像:<input type='file' name='pic'></p>
  <input type='hidden' name='author' value='{{ user.username }}'>
  <input type='submit' value='作成する'>
</form>
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-dark" role="alert">
  削除確認
  <div align="right"><a href="#" class="badge badge-primary">User</a></div>
</div>
{% endblock header %}

{% block content %}
<div class='container'>
  <div class="alert alert-info" role="alert">
    <p>タイトル:{{ item.title }}</p>
    <p>投稿者:{{ item.author }}</p>
    <p><img src='{{ item.pic.url }}' width=300></p>
    <p>コメント:{{ item.coment }}</p>
  </div>
</div>
<form action='' method='post'>{% csrf_token %}
  <input type='submit' value='削除する'>
</form>
<a href="{% url 'tweetapp:list' %}" class="btn btn-primary " role="button" aria-pressed="true">戻る</a>

{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-dark" role="alert">
  Pic Tweet
  <div align="right"><a href="#" class="badge badge-primary">User</a></div>
</div>
{% endblock header %}

{% block content %}
<div class='container'>
  <div class="alert alert-info" role="alert">
    <p>タイトル:{{ item.title }}</p>
    <p>投稿者:{{ item.author }}</p>
    <p><img src='{{ item.pic.url }}' width=300></p>
    <p>コメント:{{ item.coment }}</p>

  </div>
</div>
<a href="{% url 'tweetapp:list' %}" class="btn btn-primary " role="button" aria-pressed="true">戻る</a>

{% endblock content %}

templates/list.html
{% extends 'base.html' %}

{% block header %}
<div class="alert alert-dark" role="alert">
  Pic Tweet
  <div align="right"><a href="{% url 'tweetapp:create' %}" class="badge badge-primary">新規投稿</a></div>
  <div align="right"><a href="#" class="badge badge-primary">User</a></div>
  <div align="right"><a href="{% url 'logout' %}" class="badge badge-primary">ログアウト</a></div>
</div>
{% endblock header %}

{% block content %}
{% for item in object_list %}
<div class='container'>
  <div class="alert alert-info" role="alert">
    <p>タイトル:{{ item.title }}</p>
    <p>投稿者:{{ item.author }}</p>
    <p><img src='{{ item.pic.url }}' width=300></p>
    <a href="{% url 'tweetapp:detail'　pk=item.id %}" class="btn btn-primary " role="button" aria-pressed="true">詳細</a>
    {% if item.author == user.username %}
      <a href="{% url 'tweetapp:update' pk=item.id %}" class="btn btn-success " role="button" aria-pressed="true">編集</a>
      <a href="{% url 'tweetapp:delete' pk=item.id %}" class="btn btn-danger " role="button" aria-pressed="true">削除</a>
    {% endif %}
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/update.html
{% extends 'base.html' %}

{% block content %}
<form action='' method='POST'>{% csrf_token %}
  {{ form.title }}
  {{ form.coment }}
  {{ form.pic }}
  <input type='submit' value='更新する'>
</form>  
{% endblock content %}